"""empty message

Revision ID: 3eb24dbc8b59
Revises: 252c4e788a93
Create Date: 2014-08-18 19:54:09.376000

"""

# revision identifiers, used by Alembic.
revision = '3eb24dbc8b59'
down_revision = '252c4e788a93'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_image', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile_image')
    ### end Alembic commands ###
